-- 리뷰테이블 생성 --
CREATE TABLE REVIEW_TBL
( RE_NO NUMBER PRIMARY KEY,
RE_WRITER VARCHAR2(40) REFERENCES USER_TBL(USER_NICKNAME),
RE_REF_NO NUMBER REFERENCES MP_TBL(MP_NO),
RE_REF_NAME VARCHAR2(40) REFERENCES MP_TBL(MP_NAME),
RE_CONTENT LONG NOT NULL,
RE_GRADE NUMBER CHECK ( RE_GRADE IN ( 1, 2, 3, 4, 5 ) ) NOT NULL,
RE_RECOMMEND_CNT NUMBER DEFAULT 0,
RE_REGIDATE DATE DEFAULT SYSDATE NOT NULL,
RE_IMG_URL VARCHAR2(1000)
);
CREATE SEQUENCE REVIEW_SEQ;

SELECT * FROM REVIEW_TBL;


SELECT TO_CHAR( ( SELECT BOARD_REGIDATE FROM BOARD_TBL 
WHERE BOARD_NO = 1), 'yyyy-mm-dd hh24:mi:ss') from dual;


SELECT * FROM REVIEW_TBL
WHERE RE_REF_NO IN (SELECT MP_NO FROM MP_TBL WHERE MP_KIND IN('양식'));




UPDATE MP_TBL
SET MP_RE_CNT = (SELECT COUNT(RE_NO) FROM REVIEW_TBL WHERE RE_REF_NO = 1),
MP_AVG_GRADE = (SELECT AVG(RE_GRADE) FROM REVIEW_TBL WHERE RE_REF_NO = 1),
MP_RE_GRADE = (SELECT SUM(RE_GRADE - 2) FROM REVIEW_TBL WHERE RE_REF_NO = 1)
WHERE MP_NO = 1;

SELECT COUNT(RE_NO) FROM REVIEW_TBL WHERE RE_REF_NO = 1;
SELECT AVG(RE_GRADE) FROM REVIEW_TBL WHERE RE_REF_NO = 1;
SELECT SUM(RE_GRADE - 2) FROM REVIEW_TBL WHERE RE_REF_NO = 1; 

SELECT ((SELECT COUNT(RE_NO) FROM REVIEW_TBL WHERE RE_REF_NO = 1) +
(SELECT AVG(RE_GRADE) FROM REVIEW_TBL WHERE RE_REF_NO = 1) * 100 ) FROM DUAL;